const DEFAULT_SYMBOLS=[
{ticker:'GOOGL',tv:'NASDAQ:GOOGL',name:'Alphabet Inc.',exchange:'NASDAQ',sector:'Technology',industry:'Internet Content',domain:'google.com',last:338.50,change:5.90,pct:1.77},
{ticker:'AAPL',tv:'NASDAQ:AAPL',name:'Apple Inc.',exchange:'NASDAQ',sector:'Technology',industry:'Consumer Electronics',domain:'apple.com',last:332.27,change:5.70,pct:1.75},
{ticker:'AMZN',tv:'NASDAQ:AMZN',name:'Amazon.com, Inc.',exchange:'NASDAQ',sector:'Consumer',industry:'Internet Retail',domain:'amazon.com',last:256.78,change:4.89,pct:1.94},
{ticker:'NVDA',tv:'NASDAQ:NVDA',name:'NVIDIA Corporation',exchange:'NASDAQ',sector:'Technology',industry:'Semiconductors',domain:'nvidia.com',last:218.29,change:-0.07,pct:-0.03},
{ticker:'GLD',tv:'AMEX:GLD',name:'SPDR Gold Shares',exchange:'AMEX',sector:'ETF',industry:'Gold',domain:'ssga.com',last:398.77,change:2.41,pct:.61},
{ticker:'MU',tv:'NASDAQ:MU',name:'Micron Technology, Inc.',exchange:'NASDAQ',sector:'Technology',industry:'Semiconductors',domain:'micron.com',last:975.26,change:-2.15,pct:-.22},
{ticker:'ASML',tv:'NASDAQ:ASML',name:'ASML Holding N.V.',exchange:'NASDAQ',sector:'Technology',industry:'Semiconductor Equipment',domain:'asml.com',last:1698.30,change:10.87,pct:.64},
{ticker:'LRCX',tv:'NASDAQ:LRCX',name:'Lam Research Corporation',exchange:'NASDAQ',sector:'Technology',industry:'Semiconductor Equipment',domain:'lamresearch.com',last:298.22,change:.21,pct:.07},
{ticker:'CAT',tv:'NYSE:CAT',name:'Caterpillar Inc.',exchange:'NYSE',sector:'Industrials',industry:'Machinery',domain:'caterpillar.com',last:818.57,change:13.57,pct:1.69},
{ticker:'PLTR',tv:'NASDAQ:PLTR',name:'Palantir Technologies Inc.',exchange:'NASDAQ',sector:'Technology',industry:'Software',domain:'palantir.com',last:167.23,change:1.37,pct:.83},
{ticker:'AMAT',tv:'NASDAQ:AMAT',name:'Applied Materials, Inc.',exchange:'NASDAQ',sector:'Technology',industry:'Semiconductor Equipment',domain:'appliedmaterials.com',last:456.49,change:2.48,pct:.55},
{ticker:'ANET',tv:'NYSE:ANET',name:'Arista Networks, Inc.',exchange:'NYSE',sector:'Technology',industry:'Networking',domain:'arista.com',last:199.59,change:10.60,pct:5.61},
{ticker:'CME',tv:'NASDAQ:CME',name:'CME Group Inc.',exchange:'NASDAQ',sector:'Financials',industry:'Exchanges',domain:'cmegroup.com',last:275.54,change:1.47,pct:.54},
{ticker:'RTX',tv:'NYSE:RTX',name:'RTX Corporation',exchange:'NYSE',sector:'Industrials',industry:'Aerospace & Defense',domain:'rtx.com',last:197.68,change:-.44,pct:-.22}
];
const RANGE_MAP=[['1D','1D','5'],['5D','5D','15'],['1M','1M','60'],['6M','6M','D'],['YTD','YTD','D'],['1Y','12M','D'],['5Y','60M','W'],['10Y','120M','W'],['ALL','ALL','M']];
let watchlist=loadWatchlist();
let selectedTicker=watchlist.some(x=>x.ticker==='NVDA')?'NVDA':(watchlist[0]?.ticker||'');
let activeRange='6M',chartLoadToken=0,techLoadToken=0;
const marketDataCache=new Map();
function loadWatchlist(){try{const s=JSON.parse(localStorage.getItem('stock-monitor-watchlist')||'null');if(Array.isArray(s)&&s.length)return s}catch{}return DEFAULT_SYMBOLS}
function persist(){localStorage.setItem('stock-monitor-watchlist',JSON.stringify(watchlist))}
function logoUrl(item){return item.domain?`https://www.google.com/s2/favicons?domain=${encodeURIComponent(item.domain)}&sz=64`:'https://www.google.com/s2/favicons?domain=tradingview.com&sz=64'}
function fmtPrice(v){return typeof v==='number'?v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}
function fmtSigned(v,d=2){return typeof v==='number'?`${v>=0?'+':''}${v.toFixed(d)}`:'—'}
function selected(){return watchlist.find(x=>x.ticker===selectedTicker)||null}
function renderWatchlist(){const rows=document.getElementById('watchRows');rows.innerHTML='';document.getElementById('watchCount').textContent=watchlist.length;if(!watchlist.length){rows.innerHTML='<div class="empty-note">NO INSTRUMENTS. ADD A SYMBOL ABOVE.</div>';return}watchlist.forEach(item=>{const row=document.createElement('div');row.className=`watch-row ${item.ticker===selectedTicker?'active':''}`;row.innerHTML=`<div class="symbol-cell"><img src="${logoUrl(item)}" alt=""><span>${item.ticker}</span></div><div class="num">${fmtPrice(item.last)}</div><div class="num ${item.change>=0?'up':'down'}">${fmtSigned(item.change)}</div><div class="num ${item.pct>=0?'up':'down'}">${fmtSigned(item.pct)}%</div><button class="delete-btn" type="button" title="DELETE ${item.ticker}" aria-label="DELETE ${item.ticker}"><svg viewBox="0 0 24 24" fill="none" stroke-width="1.9"><path d="M4 7h16M9 7V4h6v3m-9 0 1 13h10l1-13M10 11v5m4-5v5"/></svg></button>`;row.addEventListener('click',()=>selectTicker(item.ticker));row.querySelector('.delete-btn').addEventListener('click',e=>{e.stopPropagation();deleteTicker(item.ticker)});rows.appendChild(row)})}
function selectTicker(ticker){if(!watchlist.some(x=>x.ticker===ticker))return;selectedTicker=ticker;renderAll()}
function deleteTicker(ticker){const was=selectedTicker===ticker;watchlist=watchlist.filter(x=>x.ticker!==ticker);if(was)selectedTicker=watchlist[0]?.ticker||'';persist();renderAll()}
function addTicker(){const input=document.getElementById('symbolInput'),raw=input.value.trim().toUpperCase().replace(/[^A-Z0-9.-]/g,'');if(!raw)return;if(watchlist.some(x=>x.ticker===raw)){selectedTicker=raw;input.value='';renderAll();return}watchlist.unshift({ticker:raw,tv:`NASDAQ:${raw}`,name:raw,exchange:'NASDAQ',sector:'—',industry:'—',domain:'',last:null,change:null,pct:null});selectedTicker=raw;persist();input.value='';renderAll()}
function renderHero(item){if(!item)return;document.getElementById('ticker').textContent=item.ticker;document.getElementById('companyName').textContent=item.name||item.ticker;document.getElementById('exchangeTag').textContent=item.exchange||'—';document.getElementById('sectorTag').textContent=item.sector||'—';document.getElementById('industryTag').textContent=item.industry||'—';document.getElementById('companyLogo').src=logoUrl(item);document.getElementById('quotePrice').innerHTML=typeof item.last==='number'?`${fmtPrice(item.last)} <small>USD</small>`:'— <small>USD</small>';const c=document.getElementById('quoteChange');if(typeof item.change==='number'&&typeof item.pct==='number'){const up=item.change>=0;c.className=`quote-change ${up?'up':'down'}`;c.textContent=`${fmtSigned(item.change)} (${fmtSigned(item.pct)}%) ${up?'▲':'▼'}`}else{c.className='quote-change muted';c.textContent='LIVE QUOTE SOURCE NOT CONNECTED YET'}}
function renderRanges(){const h=document.getElementById('ranges');h.innerHTML='';RANGE_MAP.forEach(([label,range])=>{const b=document.createElement('button');b.className=`range-btn ${range===activeRange?'active':''}`;b.textContent=label;b.onclick=()=>{activeRange=range;renderRanges();renderChart(selected())};h.appendChild(b)})}
function renderMetricsFromCandles(c){if(!c?.length)return;const z=c[c.length-1],last252=c.slice(-252),high52=Math.max(...last252.map(x=>x.high)),low52=Math.min(...last252.map(x=>x.low));const vals=[['OPEN',fmtPrice(z.open)],['HIGH',fmtPrice(z.high)],['LOW',fmtPrice(z.low)],['VOLUME',z.volume?Math.round(z.volume).toLocaleString('en-US'):'—'],['MARKET CAP','—'],['P/E','—'],['52W HIGH',fmtPrice(high52)],['52W LOW',fmtPrice(low52)]];document.getElementById('metrics').innerHTML=vals.map(([k,v])=>`<div class="metric"><div class="metric-label">${k}</div><div class="metric-value">${v}</div></div>`).join('')}
function pctFrom(c,n){if(c.length<=n)return null;const a=c[c.length-1].close,b=c[c.length-1-n].close;return b?100*(a/b-1):null}
function renderPerformance(c){const values=[['1 DAY',pctFrom(c,1)],['5 DAYS',pctFrom(c,5)],['1 MONTH',pctFrom(c,21)],['6 MONTHS',pctFrom(c,126)],['YEAR TO DATE',null],['1 YEAR',pctFrom(c,252)],['5 YEARS',null],['10 YEARS',null],['ALL TIME',null]];const nowYear=new Date((c[c.length-1]?.time||0)*1000).getUTCFullYear(),firstY=c.find(x=>new Date(x.time*1000).getUTCFullYear()===nowYear);if(firstY)values[4][1]=100*(c[c.length-1].close/firstY.close-1);document.getElementById('performanceRows').innerHTML=values.map(([l,v])=>`<div class="perf-row"><span>${l}</span><strong class="${v==null?'muted':v>=0?'up':'down'}">${v==null?'—':`${v>=0?'+':''}${v.toFixed(2)}%`}</strong></div>`).join('')}
function renderEmptyMetrics(){document.getElementById('metrics').innerHTML=['OPEN','HIGH','LOW','VOLUME','MARKET CAP','P/E','52W HIGH','52W LOW'].map(k=>`<div class="metric"><div class="metric-label">${k}</div><div class="metric-value">—</div></div>`).join('');document.getElementById('performanceRows').innerHTML=['1 DAY','5 DAYS','1 MONTH','6 MONTHS','YEAR TO DATE','1 YEAR','5 YEARS','10 YEARS','ALL TIME'].map(k=>`<div class="perf-row"><span>${k}</span><strong class="muted">—</strong></div>`).join('')}
function loadScript(src){return new Promise((resolve,reject)=>{const e=[...document.scripts].find(s=>s.src===src);if(e&&window.TradingView)return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function renderChart(item){if(!item)return;const token=++chartLoadToken,h=document.getElementById('chartHost');h.innerHTML='<div class="empty-note">LOADING CHART…</div>';try{await loadScript('https://s3.tradingview.com/tv.js');if(token!==chartLoadToken)return;const cfg=RANGE_MAP.find(x=>x[1]===activeRange)||RANGE_MAP[3];h.innerHTML='<div id="tvChart" style="height:100%;width:100%"></div>';new TradingView.widget({autosize:true,symbol:item.tv,interval:cfg[2],range:cfg[1],timezone:'Etc/UTC',theme:'dark',style:'3',locale:'en',enable_publishing:false,hide_top_toolbar:true,hide_legend:false,save_image:false,backgroundColor:'#050b0e',gridColor:'rgba(120,145,155,.10)',container_id:'tvChart'})}catch{h.innerHTML='<div class="empty-note">TRADINGVIEW CHART COULD NOT BE LOADED.</div>'}}
async function fetchDailyCandles(item){const key=item.ticker;if(marketDataCache.has(key))return marketDataCache.get(key);const p=(async()=>{const symbol=encodeURIComponent(item.yahoo||item.ticker),url=`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}?range=2y&interval=1d&includePrePost=false&events=div%2Csplits`,r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`MARKET DATA ${r.status}`);const d=await r.json(),res=d?.chart?.result?.[0],q=res?.indicators?.quote?.[0];if(!res||!q)throw new Error('NO MARKET DATA');const out=[];(res.timestamp||[]).forEach((t,i)=>{const open=q.open?.[i],high=q.high?.[i],low=q.low?.[i],close=q.close?.[i],volume=q.volume?.[i];if([open,high,low,close].every(Number.isFinite))out.push({time:t,open,high,low,close,volume:Number.isFinite(volume)?volume:0})});if(out.length<220)throw new Error('NOT ENOUGH HISTORY');return out})();marketDataCache.set(key,p);try{return await p}catch(e){marketDataCache.delete(key);throw e}}
function average(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN}function sma(v,p){return v.length>=p?average(v.slice(-p)):NaN}function emaSeries(v,p){if(v.length<p)return[];const k=2/(p+1),o=new Array(v.length).fill(NaN);let prev=average(v.slice(0,p));o[p-1]=prev;for(let i=p;i<v.length;i++){prev=v[i]*k+prev*(1-k);o[i]=prev}return o}function lastFinite(a){for(let i=a.length-1;i>=0;i--)if(Number.isFinite(a[i]))return a[i];return NaN}
function rsi(v,p=14){if(v.length<=p)return NaN;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];if(d>=0)g+=d;else l-=d}let ag=g/p,al=l/p;for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p}if(al===0)return 100;const rs=ag/al;return 100-100/(1+rs)}
function macd(v){const e12=emaSeries(v,12),e26=emaSeries(v,26),m=[];for(let i=0;i<v.length;i++)m.push(Number.isFinite(e12[i])&&Number.isFinite(e26[i])?e12[i]-e26[i]:NaN);const clean=m.filter(Number.isFinite),sig=emaSeries(clean,9);return{macd:lastFinite(m),signal:lastFinite(sig)}}
function stochastic(c,p=14){if(c.length<p+2)return{k:NaN,d:NaN};const ks=[];for(let x=2;x>=0;x--){const end=c.length-x,s=c.slice(end-p,end),hh=Math.max(...s.map(z=>z.high)),ll=Math.min(...s.map(z=>z.low)),cl=c[end-1].close;ks.push(hh===ll?50:100*(cl-ll)/(hh-ll))}return{k:ks[2],d:average(ks)}}
function cci(c,p=20){if(c.length<p)return NaN;const t=c.slice(-p).map(z=>(z.high+z.low+z.close)/3),m=average(t),md=average(t.map(x=>Math.abs(x-m)));return md?(t[t.length-1]-m)/(.015*md):0}
function williamsR(c,p=14){if(c.length<p)return NaN;const s=c.slice(-p),hh=Math.max(...s.map(z=>z.high)),ll=Math.min(...s.map(z=>z.low)),cl=s[s.length-1].close;return hh===ll?-50:-100*(hh-cl)/(hh-ll)}
function adx(c,p=14){if(c.length<p*2+2)return{adx:NaN,plus:NaN,minus:NaN};const tr=[],pd=[],md=[];for(let i=1;i<c.length;i++){const z=c[i],q=c[i-1],up=z.high-q.high,down=q.low-z.low;tr.push(Math.max(z.high-z.low,Math.abs(z.high-q.close),Math.abs(z.low-q.close)));pd.push(up>down&&up>0?up:0);md.push(down>up&&down>0?down:0)}let atr=tr.slice(0,p).reduce((a,b)=>a+b,0),ps=pd.slice(0,p).reduce((a,b)=>a+b,0),ms=md.slice(0,p).reduce((a,b)=>a+b,0),dx=[];for(let i=p;i<tr.length;i++){if(i>p){atr=atr-atr/p+tr[i];ps=ps-ps/p+pd[i];ms=ms-ms/p+md[i]}const plus=100*ps/atr,minus=100*ms/atr,d=(plus+minus)?100*Math.abs(plus-minus)/(plus+minus):0;dx.push({d,plus,minus})}if(dx.length<p)return{adx:NaN,plus:NaN,minus:NaN};let a=average(dx.slice(0,p).map(x=>x.d));for(let i=p;i<dx.length;i++)a=(a*(p-1)+dx[i].d)/p;const z=dx[dx.length-1];return{adx:a,plus:z.plus,minus:z.minus}}
function calculateTechnicalRating(c){const closes=c.map(x=>x.close),last=closes.at(-1),signals=[],add=(name,signal,value)=>signals.push({name,signal,value});[10,20,50,100,200].forEach(p=>{const v=sma(closes,p);if(Number.isFinite(v))add(`SMA ${p}`,last>v?'BUY':last<v?'SELL':'NEUTRAL',v)});[10,20,50,100,200].forEach(p=>{const v=lastFinite(emaSeries(closes,p));if(Number.isFinite(v))add(`EMA ${p}`,last>v?'BUY':last<v?'SELL':'NEUTRAL',v)});const rv=rsi(closes);add('RSI 14',rv<30?'BUY':rv>70?'SELL':'NEUTRAL',rv);const mc=macd(closes);add('MACD',mc.macd>mc.signal?'BUY':mc.macd<mc.signal?'SELL':'NEUTRAL',mc.macd-mc.signal);const st=stochastic(c);add('STOCHASTIC',st.k<20&&st.k>st.d?'BUY':st.k>80&&st.k<st.d?'SELL':'NEUTRAL',st.k);const cv=cci(c);add('CCI 20',cv<-100?'BUY':cv>100?'SELL':'NEUTRAL',cv);const wr=williamsR(c);add('WILLIAMS %R',wr<-80?'BUY':wr>-20?'SELL':'NEUTRAL',wr);const mom=closes.length>10?last-closes[closes.length-11]:NaN;add('MOMENTUM 10',mom>0?'BUY':mom<0?'SELL':'NEUTRAL',mom);const roc=closes.length>12?100*(last/closes[closes.length-13]-1):NaN;add('ROC 12',roc>0?'BUY':roc<0?'SELL':'NEUTRAL',roc);const ax=adx(c);add('ADX 14',ax.adx<20?'NEUTRAL':ax.plus>ax.minus?'BUY':'SELL',ax.adx);const valid=signals.filter(x=>Number.isFinite(x.value)),buy=valid.filter(x=>x.signal==='BUY').length,sell=valid.filter(x=>x.signal==='SELL').length,neutral=valid.filter(x=>x.signal==='NEUTRAL').length,total=Math.max(1,buy+sell+neutral),score=100*(buy-sell)/total,rating=score>=60?'STRONG BUY':score>=20?'BUY':score<=-60?'STRONG SELL':score<=-20?'SELL':'NEUTRAL';return{rating,score,buy,sell,neutral,total,signals:valid}}
function polar(cx,cy,r,deg){const a=(deg-90)*Math.PI/180;return{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)}}function arcPath(cx,cy,r,a0,a1){const s=polar(cx,cy,r,a1),e=polar(cx,cy,r,a0);return`M ${s.x.toFixed(2)} ${s.y.toFixed(2)} A ${r} ${r} 0 ${a1-a0<=180?0:1} 0 ${e.x.toFixed(2)} ${e.y.toFixed(2)}`}function gaugeColor(r){return r.includes('BUY')?'#00e6b3':r.includes('SELL')?'#ff4058':'#d2d9dc'}
function renderGauge(result){const host=document.getElementById('techHost'),angle=-90+((Math.max(-100,Math.min(100,result.score))+100)/200)*180,center={x:360,y:292},needle=polar(center.x,center.y,150,angle),segs=[[-90,-54,'#ff4058'],[-54,-18,'#ff9e32'],[-18,18,'#76848b'],[18,54,'#00bfa5'],[54,90,'#00e6b3']],labels=[[-72,'STRONG SELL'],[-36,'SELL'],[0,'NEUTRAL'],[36,'BUY'],[72,'STRONG BUY']],lh=labels.map(([a,t])=>{const p=polar(center.x,center.y,205,a);return`<text x="${p.x}" y="${p.y}" text-anchor="middle" dominant-baseline="middle" class="gauge-label${t===result.rating?' active':''}">${t}</text>`}).join('');host.innerHTML=`<div class="technical-panel"><div class="technical-status">DAILY · OWN CALCULATION · ${result.total} SIGNALS</div><div class="gauge-wrap"><svg class="gauge-svg" viewBox="0 0 720 370" role="img" aria-label="${result.rating}">${segs.map(([a,b,c])=>`<path d="${arcPath(center.x,center.y,154,a,b)}" fill="none" stroke="${c}" stroke-width="28" stroke-linecap="round"/>`).join('')}${lh}<line x1="${center.x}" y1="${center.y}" x2="${needle.x}" y2="${needle.y}" stroke="${gaugeColor(result.rating)}" stroke-width="6" stroke-linecap="round"/><circle cx="${center.x}" cy="${center.y}" r="12" fill="#fff"/><text x="${center.x}" y="244" text-anchor="middle" class="gauge-main" fill="${gaugeColor(result.rating)}">${result.rating}</text><text x="${center.x}" y="274" text-anchor="middle" class="gauge-score">SCORE ${result.score>=0?'+':''}${result.score.toFixed(0)}</text></svg></div><div class="gauge-counts"><div class="gauge-count sell"><span>SELL</span><strong>${result.sell}</strong></div><div class="gauge-count neutral"><span>NEUTRAL</span><strong>${result.neutral}</strong></div><div class="gauge-count buy"><span>BUY</span><strong>${result.buy}</strong></div></div></div>`}
async function renderTechnicals(item){if(!item)return;const token=++techLoadToken,h=document.getElementById('techHost');h.innerHTML='<div class="empty-note">CALCULATING TECHNICALS…</div>';try{const c=await fetchDailyCandles(item);if(token!==techLoadToken)return;const z=c.at(-1),p=c.at(-2);item.last=z.close;item.change=z.close-p.close;item.pct=100*item.change/p.close;renderWatchlist();renderHero(item);renderMetricsFromCandles(c);renderPerformance(c);renderGauge(calculateTechnicalRating(c));document.getElementById('lastUpdate').textContent='CHART BY TRADINGVIEW · TECHNICALS CALCULATED BY STOCK MONITOR'}catch(e){if(token!==techLoadToken)return;h.innerHTML='<div class="empty-note">TECHNICAL DATA UNAVAILABLE<br><span class="muted">CHECK MARKET DATA CONNECTION</span></div>';console.error(e)}}
function renderAll(){renderWatchlist();renderRanges();const item=selected();if(!item){renderEmptyMetrics();return}renderHero(item);renderEmptyMetrics();renderChart(item);renderTechnicals(item)}
document.getElementById('addBtn').addEventListener('click',addTicker);document.getElementById('symbolInput').addEventListener('keydown',e=>{if(e.key==='Enter')addTicker()});renderAll();